<a href="https://colab.research.google.com/github/ace2884/mlds-lab/blob/main/Copy_of_week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
import pandas as pd
import numpy as np


In [ ]:
#Load dataset
iris=datasets.load_iris()
print("Iris Data set loaded...")

Iris Data set loaded...


In [ ]:
#Split the data into train and test samples
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.1)
print("Dataset is split into training and testing...")
print("Size of training data and its label",x_train.shape,y_train.shape)
print("Size of training data and its label",x_test.shape,y_test.shape)


# prints Label no. and their names
for i in range(len(iris.target_names)):
  print("Label", i , "-",str(iris.target_names[i]))
  #create object of KNN classifer
classifer = KNeighborsClassifier(n_neighbors=1)


#perform Training
classifer.fit(x_train, y_train)#perform teating
y_pred=classifer.predict(x_test)



#Display the results
print("Results of Classification using K-nn with K=1")
for r in range(0,len(x_test)):
  print(" sample:", str(x_test[r]), " Actual-label:",str(y_test[r]), " predict-label:", str(y_pred[r]))
print("Classification Accuracy :" , classifer.score(x_test,y_test))

Dataset is split into training and testing...
Size of training data and its label (135, 4) (135,)
Size of training data and its label (15, 4) (15,)
Label 0 - setosa
Label 1 - versicolor
Label 2 - virginica
Results of Classification using K-nn with K=1
 sample: [4.8 3.4 1.6 0.2]  Actual-label: 0  predict-label: 0
 sample: [4.7 3.2 1.6 0.2]  Actual-label: 0  predict-label: 0
 sample: [5.8 2.7 5.1 1.9]  Actual-label: 2  predict-label: 2
 sample: [6.  2.7 5.1 1.6]  Actual-label: 1  predict-label: 2
 sample: [7.7 2.8 6.7 2. ]  Actual-label: 2  predict-label: 2
 sample: [7.  3.2 4.7 1.4]  Actual-label: 1  predict-label: 1
 sample: [6.2 2.8 4.8 1.8]  Actual-label: 2  predict-label: 2
 sample: [4.6 3.4 1.4 0.3]  Actual-label: 0  predict-label: 0
 sample: [4.9 3.  1.4 0.2]  Actual-label: 0  predict-label: 0
 sample: [7.7 2.6 6.9 2.3]  Actual-label: 2  predict-label: 2
 sample: [6.2 2.2 4.5 1.5]  Actual-label: 1  predict-label: 1
 sample: [6.7 3.  5.2 2.3]  Actual-label: 2  predict-label: 2
 sam

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('Accuracy Ketrics')
print(classification_report(y_test,y_pred))


Confusion Matrix
[[6 0 0]
 [0 3 1]
 [0 0 5]]
Accuracy Ketrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.75      0.86         4
           2       0.83      1.00      0.91         5

    accuracy                           0.93        15
   macro avg       0.94      0.92      0.92        15
weighted avg       0.94      0.93      0.93        15

